### ISSUE TITLE
Documento con información de los autores

### ISSUE THREAD

**Issue by Danijg2k** [dangilcal/Practica_21#13]
Nos vendría bien actualizar el README.md (documento de texto) que tenemos en la carpeta. Tenemos puesto que es una página de escritoras, pero vendría bien añadir los nombres de los integrantes del grupo.

**Comment by Danijg2k** [comment]
Buen trabajo!

**Comment by Danijg2k** [comment]
De todas formas busca el README.md y mete nuestros 4 nombres dentro porfa.

**Comment by ander5555** [comment]
he añadido los nombres de los autores en README.md
